name: MinecraftGuiTemplate
version: '${project.version}'
main: minecraftguitemplate.me.GuiTemplate
api-version: 1.19
commands:
  mainmenu:
    description: Show guitemplate's gui
  playermenu:
    alias: [pm]
    description: Simple playermenu
